@startuml

!include ../includes/amiga.iuml

actor lorem as A
participant dolor as P1
queue sit as Q
box ipsum
  participant consectetur as P2 <<amet>>
  database adipiscing as DB
end box

A -> P1++ : elit

P1 -> Q : <back:$RED>sed do\n\
<back:$RED>eiusmod\n\
<back:$RED>tempor

P1 -> P1 : incididunt

return

Q -> P2++ : <back:$BG>ut labore

P2 -[$ORANGE]\ DB ++ $ORANGE : et dolore

P2 --

destroy DB

note over A, Q
  <b>Ut</b> <u>enim ad</u> <i>minim</i>
  ""veniam"", [[example.org quis nostrud]]
  <w>exercitation</w> <s:$RED>ullamco</s>
end note

== magna aliqua ==

group laboris
  -> P2++ : <back:$BG>aliquip ex
  return <back:$BG>ea commodo
end

@enduml
