' MIT License
'
' Copyright (c) 2021 Matthew Leather
'
' Permission is hereby granted, free of charge, to any person obtaining a copy
' of this software and associated documentation files (the "Software"), to deal
' in the Software without restriction, including without limitation the rights
' to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
' copies of the Software, and to permit persons to whom the Software is
' furnished to do so, subject to the following conditions:
'
' The above copyright notice and this permission notice shall be included in all
' copies or substantial portions of the Software.
'
' THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
' IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
' FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
' AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
' LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
' OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
' SOFTWARE.

!$BG = "white"
!$FG = "black"

!ifndef $FONT_NAME
  !$FONT_NAME = "Verdana"
!endif

!ifndef $FONT_NAME_MONOSPACED
  !$FONT_NAME_MONOSPACED = "Courier"
!endif

<style>
  root {
    BackgroundColor $BG
    FontColor $FG
    FontName $FONT_NAME
    HyperLinkColor blue
    LineColor $FG
    LineThickness 1
    Margin 5
  }
  caption {
    LineThickness 0
  }
  footer {
    LineThickness 0
  }
  header {
    LineThickness 0
  }
  node {
    MaximumWidth 300
  }
  title {
    FontSize 22
    LineThickness 0
  }
</style>

skinparam ArrowLollipopColor $FG
skinparam BackgroundColor $BG
skinparam DefaultFontName $FONT_NAME
skinparam DefaultMonospacedFontName $FONT_NAME_MONOSPACED
skinparam Footbox hide
skinparam LifelineStrategy nosolid
skinparam ParticipantPadding 10
skinparam SequenceLifeLineBorderColor $FG
skinparam Shadowing false
skinparam UseBetaStyle true

skinparam Activity {
  BackgroundColor $BG
  BarColor $FG
  BorderColor $FG
  FontColor $FG
  FontName $FONT_NAME
}
skinparam Boundary {
  FontColor $FG
}
skinparam Box {
  Padding 5
}
skinparam CircledCharacter {
  FontColor $FG
  FontName $FONT_NAME_MONOSPACED
  Radius 9
}
skinparam Class {
  BackgroundColor $BG
  BorderColor $FG
  FontColor $FG
  FontName $FONT_NAME
}
skinparam ClassAttribute {
  FontColor $FG
  FontName $FONT_NAME
}
skinparam ClassStereotype {
  FontColor $FG
  FontName $FONT_NAME
}
skinparam Footer {
  FontColor $FG
  FontName $FONT_NAME
}
skinparam Header {
  FontColor $FG
  FontName $FONT_NAME
}
skinparam Hyperlink {
  Color blue
}
skinparam IconPackage {
  Color $FG
  BackgroundColor $BG
}
skinparam IconPrivate {
  Color $FG
  BackgroundColor $BG
}
skinparam IconProtected {
  Color $FG
  BackgroundColor $BG
}
skinparam IconPublic {
  Color $FG
  BackgroundColor $BG
}
skinparam Note {
  FontColor $FG
  FontName $FONT_NAME
}
skinparam Package {
  BorderColor $FG
  FontColor $FG
  FontName $FONT_NAME
}
skinparam State {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam StereotypeA {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam StereotypeC {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam StereotypeE {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam StereotypeI {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam StereotypeN {
  BackgroundColor $BG
  BorderColor $FG
}
skinparam UseCaseStereoType {
  FontColor $FG
  FontName $FONT_NAME
}
