name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'generated_images/**'
  workflow_dispatch:
  

jobs:
  generate_images:
    name: Generate Images
    runs-on: ubuntu-latest
    env:
      PLANTUML_VERSION: 1.2021.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update OS Package Lists
        run:  sudo apt-get update

      - name: Install OS Packages
        run:  sudo apt-get install default-jre-headless graphviz
      
      - name: Install PlantUML
        # Not using "apt-get install plantuml" because it's an old version
        run:  wget -q -O "${GITHUB_WORKSPACE}/plantuml.jar" "https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"

      - name: Make output dir
        run:  mkdir -p generated_images

      - name: Run PlantUML
        run:  |
          java \
            -jar "${GITHUB_WORKSPACE}/plantuml.jar" \
            -headless \
            -nometadata \
            -o "${GITHUB_WORKSPACE}/generated_images" \
            -verbose \
            examples/*.puml
          ls -l generated_images
          
      - name: Push Changes
        run: |
          # TODO only if changes
          git add -v generated_images/*.png
          git commit \
            --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" \
            --message "Update Generated Images"
          git push
