name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/generated_images/**'
  workflow_dispatch:
  
jobs:
  generate_images:
    name: Generate Images
    runs-on: ubuntu-latest
    env:
      OUTPUT_DIR: docs/generated_images
      PLANTUML_VERSION: 1.2021.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"

      - name: Setup Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
    
      - name: Update OS package lists
        run:  sudo apt-get update

      - name: Install Graphviz
        run:  sudo apt-get install --no-install-recommends graphviz

      # Not using OS package here because it's always an old version
      - name: Install PlantUML
        run:  wget -q -O "${GITHUB_WORKSPACE}/plantuml.jar" "https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"

      - name: Make output dir
        run:  mkdir -p "${OUTPUT_DIR}"

      - name: Run PlantUML
        run:  |
          java \
            -jar "${GITHUB_WORKSPACE}/plantuml.jar" \
            -headless \
            -nometadata \
            -o "${GITHUB_WORKSPACE}/${OUTPUT_DIR}" \
            -verbose \
            "examples/**.puml"
        
      - name: Git add new / changed files
        id: git_add
        run: |
          git add -v "${OUTPUT_DIR}/*.png"
          set +e
          git diff-index --cached HEAD --quiet
          echo "::set-output name=has_changes::$?"

      - name: Push changes
        if: steps.git_add.outputs.has_changes == 1
        run: | 
            git commit -m "Update Generated Images"
            git push
