name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'generated_images/**'
  workflow_dispatch:
  

jobs:
  generate_images:
    name: Generate Images
    runs-on: ubuntu-latest
    env:
      PLANTUML_VERSION: 1.2021.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install OS Packages
        run: |
          sudo apt-get update
          sudo apt-get install default-jre-headless graphviz

          # Avoid Java logging "Created user preferences directory"
          #mkdir -p ~/.java/.userPrefs
      
      - name: Install PlantUML
        run: |
          # Not using "apt-get install plantuml" because it's an old version
          wget -q -O "${GITHUB_WORKSPACE}/plantuml.jar" "https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"

      - name: Run PlantUML
        run: |
          java -Djava.awt.headless=true -jar "${GITHUB_WORKSPACE}/plantuml.jar" -help
          mkdir -p generated_images
          ls -l examples/*.puml
          java \
            -jar "${GITHUB_WORKSPACE}/plantuml.jar" \
            -headless
            -o "${GITHUB_WORKSPACE}/generated_images" \
            -verbose \
            examples/*.puml
          ls -l generated_images
          
      - name: Commit Images
        run: |
          git add generated_images/*
          git commit -m "Update Generated Images"
          git push
