name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/example_images/**'
  workflow_dispatch:

jobs:
  generate_images:
    name: Generate doc files
    runs-on: ubuntu-latest
    env:
      EXAMPLE_IMAGES_DIR: docs/example_images
      PLANTUML_VERSION: 1.2021.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name  "github-actions[bot]"

      - name: Set up Java
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15

      - name: Update OS package lists
        run:  sudo apt-get update

      - name: Install Graphviz
        run:  sudo apt-get install --no-install-recommends graphviz

      # Not using OS package here because it's always an old version
      - name: Install PlantUML
        run:  wget -q -O plantuml.jar "https://repo1.maven.org/maven2/net/sourceforge/plantuml/plantuml/${PLANTUML_VERSION}/plantuml-${PLANTUML_VERSION}.jar"

      - name: Make output dir
        run: mkdir -p "${EXAMPLE_IMAGES_DIR}"

      - name: Generate images
        run:  |
          java \
            -jar plantuml.jar \
            -headless \
            -Ithemes \
            -nometadata \
            -o "${EXAMPLE_IMAGES_DIR}" \
            -verbose \
            "examples/**.puml"

      - name: Git add new or changed images
        id: git_add
        run: |
          git add -v "${EXAMPLE_IMAGES_DIR}/*.png"
          set +e
          git diff-index --cached HEAD --quiet
          echo "::set-output name=has_changes::$?"

      - name: Push changes
        if: steps.git_add.outputs.has_changes == 1
        run: |
            git commit -m "Update generated doc files"
            git push
